### ISSUE TITLE
d.ts не нужен

### ISSUE THREAD

**Issue by pongo** [zaxoavoki/ts-blog-example#4]
https://github.com/zaxoavoki/ts-blog-example/blob/a38c221ba4304e074924cb288a87c73dfbe695a3/src/types/User.d.ts#L1

Достаточно назвать файл User.ts

**Comment by zaxoavoki** [comment]
@pongo , Не сразу понял для чего было указывать [`*.d.ts`](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html)
